const keyMirror = require('keymirror');

module.exports = keyMirror({
  API_CALL: null,

  AUTHENTICATION_DATA_RESET: null,
  AUTHENTICATION_LOGIN_FAILURE: null,
  AUTHENTICATION_LOGIN_REQUEST: null,
  AUTHENTICATION_LOGIN_SUCCESS: null,
  AUTHENTICATION_REGISTER_FAILURE: null,
  AUTHENTICATION_REGISTER_REQUEST: null,
  AUTHENTICATION_REGISTER_SUCCESS: null,
});
